{
 "title": "Gym occupancy",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Climbers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(stats.gauges.gym.*.occupancy, 'Climbers')"
    }
   ]
  },
  {
   "title": "Occupancy %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(stats.gauges.gym.*.occupancy_pc, 'Occupancy')"
    }
   ]
  },
  {
   "title": "Climbing centre occupancy",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.gym.*.capacity, 'Capacity')"
    },
    {
     "target": "alias(stats.gauges.gym.*.occupancy, 'Occupancy')"
    }
   ]
  }
 ]
}